import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import "@fontsource/prompt";
import Script from "next/script";
import Menu from "@/component/menu";
import Link from "next/link";

// import LayoutProject from "@/component/layout-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/AuthContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <Link
          href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css"
          rel="stylesheet"
        />
      </head> */}
      <body className={inter.className}>
        <Script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></Script>
        <NextUIProvider>
          <AuthProvider>
            <Menu>{children}</Menu>
          </AuthProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
